version: '3.8'

services:
  dungeon-app:
    build: .
    container_name: dungeon-app
    ports:
      - "5000:5000" # Проброс порта контейнера на хост
    restart: always # Автоматический перезапуск при падении
    environment:
      - NODE_ENV=production
